name: Linux x86-64

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ runner.arch }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-gradle-

      # compile
      - name: Compile
        run: |
          docker build -t debianjbr src/test/resources/deb/
          docker run --rm -v ~/.gradle:/root/.gradle -v $(pwd):/app -w /app debianjbr ./gradlew classes -x test

      # dist
      - name: Dist
        run: |
          mkdir distributions
          
          # deb
          docker run --rm -v ~/.gradle:/root/.gradle -v $(pwd):/app -w /app debianjbr ./gradlew :dist -Dtype=deb
          sudo mv build/distributions/*.deb distributions/
          
          # clean
          docker run --rm -v ~/.gradle:/root/.gradle -v $(pwd):/app -w /app debianjbr ./gradlew clean
          
          # tar.gz and AppImage
          docker run --rm --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined -v ~/.gradle:/root/.gradle -v $(pwd):/app -w /app debianjbr ./gradlew :dist
          sudo mv build/distributions/*.tar.gz distributions/
          sudo mv build/distributions/*.AppImage distributions/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: termora-linux-x86-64
          path: |
            distributions/*.tar.gz
            distributions/*.AppImage
            distributions/*.deb
