name: Linux aarch64

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ runner.arch }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-gradle-

      - name: Package
        shell: bash
        run: |
          
          docker build -t debianjbr src/test/resources/deb/
          
          DOCKER_PARAMS="docker run --rm -v $HOME/.gradle:/root/.gradle -v $(pwd):/app -w /app"
          
          # Compile
          $DOCKER_PARAMS debianjbr bash -c './gradlew clean :check-license'
          
          # Jlink
          $DOCKER_PARAMS debianjbr bash -c './gradlew :jar :copy-dependencies :plugins:migration:build :jlink'
          
          # Package Deb
          $DOCKER_PARAMS -e TERMORA_TYPE=deb debianjbr bash -c './gradlew :jpackage && ./gradlew :dist'
          
          # Package AppImage and tar.gz
          $DOCKER_PARAMS --device /dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined debianjbr bash -c 'rm -rf build/jpackage && ./gradlew :jpackage && ./gradlew :dist'

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: termora-linux-x86-64
          path: |
            distributions/*.tar.gz
            distributions/*.AppImage
            distributions/*.deb
