name: Windows aarch64

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-11-arm
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download WiX 3.14
        run: |
          curl -L -o wix314.exe https://github.com/wixtoolset/wix3/releases/download/wix3141rtm/wix314.exe
          .\wix314.exe /quiet /norestart
          echo "C:\Program Files (x86)\WiX Toolset v3.14\bin" >> $env:GITHUB_ENV

      - name: Install zip
        run: |
          $system32 = [System.Environment]::GetEnvironmentVariable("WINDIR") + "\System32"
          Invoke-WebRequest -Uri "http://stahlworks.com/dev/zip.exe" -OutFile "$system32\zip.exe"
          Invoke-WebRequest -Uri "http://stahlworks.com/dev/unzip.exe" -OutFile "$system32\unzip.exe"

      - name: Install 7z
        uses: milliewalky/setup-7-zip@v2

      - name: Installing Java
        run: |
          curl -s --output ${{ runner.temp }}\java_package.zip -L https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-21.0.6-windows-aarch64-b895.91.zip
          unzip -q ${{ runner.temp }}\java_package.zip -d ${{ runner.temp }}\jbr
          echo "JAVA_HOME=${{ runner.temp }}\jbr\jbrsdk-21.0.6-windows-aarch64-b895.91" >> $env:GITHUB_ENV

      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-${{ runner.arch }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-gradle-

      # dist
      - run: |
          .\gradlew.bat dist --no-daemon
          .\gradlew.bat --stop

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: termora-windows-aarch64
          path: |
            build/distributions/*.zip
            build/distributions/*.exe
